### ISSUE TITLE
关于博客还是论坛的疑问

### ISSUE THREAD

**Issue by HuJJ-NB** [imuncle/gitblog#17]
* 利用issues的方式，那岂不是所有人都可以发布文章了，这应该更像是一个论坛而不是个人博客了。

* 博客应该是只有自己发布，其他人只有评论的权限。

**Comment by imuncle** [comment]
hhh是这样的，这个gitblog为了演示我把所有issue都在博客中显示出来了，我自己的博客只显示我自己发表的issue，可以在博客层面屏蔽别人的issue

**Comment by HuJJ-NB** [comment]
好嘞
